### ISSUE TITLE
When multiple destination handled and there no token set, token is undefined

### ISSUE THREAD

**Issue by killmenot** [robtweed/ewd-qoper8-express#1]
https://github.com/robtweed/ewd-qoper8-express/blob/54e3a170a2d51b0a611926968ff81691dbb1bf37/lib/microServiceRouter.js#L196-L205

Maybe the following is better:
```js
var responseObj = {
  type: message.type,
  message: {
    destinations: compositeResponse,
 }
};

if (token) {
  responseObj.message.token = token;
}
```

**Comment by robtweed** [comment]
Not sure it makes any real difference.  If token doesn't exist, message.token (line 201) won't get created anyway
