### ISSUE TITLE
Question about passing token with multiple destinations

### ISSUE THREAD

**Issue by killmenot** [robtweed/ewd-qoper8-express#2]
Hi @robtweed,

https://github.com/robtweed/ewd-qoper8-express/blob/54e3a170a2d51b0a611926968ff81691dbb1bf37/lib/microServiceRouter.js#L190-L193

Should token be deleted from every message or only from the first one?

**Comment by robtweed** [comment]
from every message - the idea is to grab an instance of a returned JWT and use that in the composite response.  It doesn't really matter which JWT is chosen - they should all be pretty much indentical
